config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  namespace :posts do
    resources :searches, only: :index
  end
  resources :posts, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  
  def self.search(search)
    return Post.all unless search
    Post.where('text LIKE(?)', "%#{search}%")
  end

  validates :text, presence: true
  validates :area, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts/searches_controller.rb
class Posts::SearchesController < ApplicationController
  
  def index
    @posts = Post.search(params[:keyword])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    #binding.pry
    Post.create(post_params)
  end

  private

  def post_params
    params.require(:post).permit(:text, :area)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts/searches_helper.rb
module Posts::SearchesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Tokyomap
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .header
      = link_to '東京 toiletmemory', root_path, class: 'header__logo'
    
    = yield

    .footer
      %ul.footer__box
        %li.footer__box__comment
          プライバシーポリシー
        %li.footer__box__comment
          東京toiletmemoryについて
      %small.footer__copyright
        © 東京toiletmemory,inc.

app/views/posts/create.html.haml
投稿ありがとうございます

app/views/posts/index.html.haml
.toilet-info
  .toilet-info__box
    = link_to posts_searches_path, class: 'toilet-info__box__search' do
      トイレを検索する

    = link_to new_post_path, class: 'toilet-info__box__register' do
      トイレを登録する

app/views/posts/new.html.haml
.form
  .form__message    　
  .form__box
    = form_with(model: @post, local: true) do |f| 
      = f.text_area :area, class: 'form__box__text', placeholder: '(例)渋谷区'
      = f.text_area :text, class: 'form__box__area', placeholder: '施設名'
      = f.submit '送信', class: 'form__box__submit'

app/views/posts/searches/index.html.haml
.search
  = form_with(url: posts_searches_path, local: true, method: :get, class: "search__form") do |f| 
    = f.text_field :keyword, placeholder: "トイレを検索する", class: "search__input" 
    = f.submit "検索", class: "search__btn"

.main
  .main__contents
    - @posts.each do |post|
      .main__contents__content
        .main__contents__content__area
          = post.area
        .main__contents__content__text
          = post.text